WebAppDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppDemo.Models;
using System.Collections.Specialized;
using System.IO;

namespace WebAppDemo.Controllers
{
	public class HomeController : BaseController
	{

		DemoMVCEntities1 db = new DemoMVCEntities1();
	
		public ActionResult Xem1(string ma)
		{
			User anh = ckec_permission(new string[] { PERMISSIONS.SACH_VIEW }, true);
			if (ma == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");
			var context = new DemoMVCEntities1();
			var ketqua = context.Saches.Find(ma);
			return View(ketqua);
		}
		public ActionResult Index(string SearchString,string SearchDate)
		{
			User anh = ckec_permission(new string[] { PERMISSIONS.SACH_VIEW }, true);
			
			if (SearchString == null && SearchDate == null)
			{
				DemoMVCEntities1 listSach = new DemoMVCEntities1();
				var ketqua = (from item in listSach.Saches
							  where item.DaXoa == false

							  select item
							  ).ToList();
				return View(ketqua);
			}
			else if (SearchString != null && SearchDate == "")
			{
				using (var context = new DemoMVCEntities1())
				{
					object[] parms =
				{
					new SqlParameter("@TenTacGia",SearchString),
					new SqlParameter("@TenCuonSach",SearchString),
					new SqlParameter("@TenNhaXuatBan",SearchString)
					};
					var data = context.Saches.SqlQuery("EXEC TimKiemTheoTen @TenTacGia,@TenCuonSach,@TenNhaXuatBan", parms).ToList();
					return View(data);
				}
			}
			else if (SearchString == "" && SearchDate != null)
			{
				using (var context = new DemoMVCEntities1())
				{
					object[] parms =
				{
					new SqlParameter("@NgayTao",SearchDate),
					new SqlParameter("@NgayXuatBan",SearchDate)
					};
					var data = context.Saches.SqlQuery("EXEC TimKiemTheoNgay @NgayTao,@NgayXuatBan", parms).ToList();
					return View(data);
				}
			}
			else
			{
				using (var context = new DemoMVCEntities1())
				{
					object[] parms =
				{
					new SqlParameter("@TenTacGia",SearchString),
					new SqlParameter("@TenCuonSach",SearchString),
					new SqlParameter("@TenNhaXuatBan",SearchString),
					new SqlParameter("@NgayTao",SearchDate),
					new SqlParameter("@NgayXuatBan",SearchDate)
					};
					var data = context.Saches.SqlQuery("EXEC TimKiemTenNgay @TenTacGia,@TenCuonSach,@TenNhaXuatBan,@NgayTao,@NgayXuatBan", parms).ToList();
					return View(data);
				}
			}
			
		}
		public ActionResult hiem()
		{
			User anh = ckec_permission(new string[] { PERMISSIONS.SACH_VIEW }, true);
			
			DemoMVCEntities1 listSach = new DemoMVCEntities1();
			var ketqua = (from item in listSach.Saches
						  where item.DaXoa == true

						  select item
						  ).ToList();
			return View(ketqua);
		}
		public ActionResult anhtu8444()
		{
			return View();
		}

		[HttpPost]
		public ActionResult anhtu8444(PhanLoaiSach model)
		{
			User anh = ckec_permission(new string[] { PERMISSIONS.SACH_VIEW }, true);
			
			try
			{
				// TODO: Add insert logic here
				var context = new DemoMVCEntities1();

				context.PhanLoaiSaches.Add(model);
				context.SaveChanges();
				return RedirectToAction("PhanLoai");


			}
			catch
			{
				return View();
			}
		}

		
	}
}

WebAppDemo/Controllers/SachController.cs
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppDemo.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Net;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Specialized;
using PagedList;




namespace WebAppDemo.Controllers
{
	public class SachController : BaseController
    {
        private DemoMVCEntities1 db = new DemoMVCEntities1();
        // GET: Sach
        public ActionResult Chart()
		{
			DemoMVCEntities1 data = new DemoMVCEntities1();
			var ketqua = data.Chart1.SqlQuery("Exec chart").ToList();

			return View(ketqua);
            
       
		}
        public ActionResult Index(string ma, int? page)
		{
            User anh = ckec_permission(new string[] { PERMISSIONS.SACH_VIEW }, true);
            if (ma == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");

            DemoMVCEntities1 listSach = new DemoMVCEntities1();
            if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            

            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 4;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);
           
                object[] parms =
            {
                    new SqlParameter("@ma",ma),
                    
                    };
                var data = listSach.Saches.SqlQuery("EXEC ListSach @ma", parms).ToList();
                return View(data.ToPagedList(pageNumber, pageSize));
            

           
        }
        public ActionResult Xem(string ma)
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.SACH_VIEW }, true);
            if (ma == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");
            var context = new DemoMVCEntities1();
            var ketqua = context.Saches.Find(ma);
            ketqua.DaXoa = false;
            context.SaveChanges();
           return RedirectToAction("Hiem","Home");
        }
        public ActionResult Edit(string id)
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.SACH_EDIT }, true);
            if (id == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPhanLoai = new SelectList(db.PhanLoaiSaches, "Ma", "TenPhanLoai", sach.MaPhanLoai);
            return View(sach);
        }

        // POST: Saches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma,MaPhanLoai,Ten,HinhBia,TomTat,Link,NgayXuatBan,NhaXuatBan,TenTacGia,DaXoa,NgayTao,NguoiTao,NgaySua,NguoiSua,NgayXoa,NguoiXoa")] Sach sach, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/"), Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    sach.HinhBia = "~/" + file.FileName;
                }
                db.Entry(sach).State = EntityState.Modified;
                    db.SaveChanges();
             
                return RedirectToAction("Xem",new {ma=sach.Ma });
            }
            ViewBag.MaPhanLoai = new SelectList(db.PhanLoaiSaches, "Ma", "TenPhanLoai", sach.MaPhanLoai);
            return View(sach);
        }

        // GET: Saches/Delete/5
        public ActionResult Delete(string id)
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.SACH_DELETE }, true);
            if (id == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");
            var context = new DemoMVCEntities1();
            var delete = context.Saches.Find(id);
            return View(delete);
        }
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection, Sach modele)
        {
            try
            {
                // TODO: Add delete logic here
                var context = new DemoMVCEntities1();
                var delete = context.Saches.Find(id);
                    delete.DaXoa = true;
                    delete.NgayXoa = DateTime.Now;
                    delete.NguoiXoa = modele.NguoiXoa;
                    context.SaveChanges();

              

                return RedirectToAction("Index","Home");

            }
            catch
            {
                return View();
            }
        }

     
        public ActionResult PhanLoai()
		{
            User anh = ckec_permission(new string[] { PERMISSIONS.PHANLOAI_VIEW }, true);
			

			DemoMVCEntities1 listPhanLoai = new DemoMVCEntities1();
              
                var ketqua = listPhanLoai.PhanLoaiSaches.SqlQuery("EXEC lisPhanLoai").ToList();
            
            return View(ketqua);
            
            
        }
       
        public ActionResult PhanLoaiDaXoa()
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.PHANLOAI_VIEW }, true);
           
            DemoMVCEntities1 listPhanLoai = new DemoMVCEntities1();
            using (var context = new DemoMVCEntities1())
            {
              
                var ketqua = context.PhanLoaiSaches.SqlQuery("EXEC lisPhanLoaiDaXoa").ToList();
				if (ketqua.ToArray().Length==0)
				{
                    ketqua = null;
                    return RedirectToAction("PhanLoai");

                }
				else
                return View(ketqua);
            }
            
            
        }
        public ActionResult CreatePhanLoai()
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.PHANLOAI_ADD }, true);
            

            return View();
        }

        [HttpPost]
        public ActionResult CreatePhanLoai(PhanLoaiSach model)
        {
            var context = new DemoMVCEntities1();
            
           
                // TODO: Add insert logic here
               if (context.PhanLoaiSaches.Find(model.Ma)==null)
			    {
                    context.PhanLoaiSaches.Add(model);
                    context.SaveChanges();
                    return RedirectToAction("PhanLoai");
                }
				else { return Content("<script language='javascript' type='text/javascript'>alert('Mã sách đã tồn tại');window.history.back();</script>"); }





        }
        public ActionResult EditPhanLoai(string ma)
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.PHANLOAI_EDIT }, true);
            if (ma == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");
            DemoMVCEntities1 context = new DemoMVCEntities1();
            var editing = context.PhanLoaiSaches.Find(ma);


            return View(editing);
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult EditPhanLoai(PhanLoaiSach model)
        {
            try
            {
                // TODO: Add update logic here
                var context = new DemoMVCEntities1();
        
                var oldItem = context.PhanLoaiSaches.Find(model.Ma);
                int i = 0;


                var ketqua = (from item in context.Saches
                              where item.MaPhanLoai == model.Ma
                              select item).ToList();
                foreach (var a in ketqua)
                {
                    i = i + 1;
                }

                if (i == 0)
                {
                    oldItem.DaXoa = model.DaXoa;

                }
			
                oldItem.TenPhanLoai = model.TenPhanLoai;
                
                oldItem.NgayTao = model.NgayTao;
                oldItem.NguoiTao = model.NguoiTao;
                oldItem.NgaySua = model.NgaySua;
                oldItem.NguoiSua = model.NguoiSua;
                oldItem.NgayXoa = model.NgayXoa;
                oldItem.NguoiXoa = model.NguoiXoa;
                
                context.SaveChanges();


                return RedirectToAction("PhanLoai");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult DeletePhanLoai(string ma)
        {
            User anh = ckec_permission(new string[] { PERMISSIONS.PHANLOAI_DELETE }, true);
            if (ma == null) return Content("<script language='javascript' type='text/javascript'>alert('Quay lại thôi bro');window.history.back();</script>");
            var context = new DemoMVCEntities1();
            var delete = context.PhanLoaiSaches.Find(ma);
            return View(delete);
        }
     
        public ActionResult RestorePhanLoai(string ma, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var context = new DemoMVCEntities1();
                var delete = context.PhanLoaiSaches.Find(ma);

WebAppDemo/Views/Home/Anhtu8444.cshtml
<div class="col-lg-6">
	<div class="card mb-4">
		<div class="card-header">
			<i class="fas fa-chart-pie me-1"></i>
			Pie Chart Example
		</div>
		<div class="card-body"><canvas id="myChart" style="width:100%;max-width:600px"></canvas></div>
		<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
	</div>
    </div>
	<script>
		var xValues = ["Italy", "France", "Spain", "USA", "Argentina"];
var yValues = [55, 49, 44, 24, 15];
var barColors = [
    "#b91d47",
    "#00aba9",
    "#2b5797",
    "#e8c3b9",
    "#1e7145"
];

new Chart("myChart", {
    type: "pie",
    data: {
        labels: xValues,
        datasets: [{
            backgroundColor: barColors,
            data: yValues
        }]
    },
    options: {
        title: {
            display: true,
            text: "World Wide Wine Production 2018"
        }
    }
});
	</script>

WebAppDemo/Views/Home/Index.cshtml
@model IEnumerable<WebAppDemo.Models.Sach>

@{
	ViewBag.Title = "Index";
}






<p>
	@Html.ActionLink("Thêm sách mới", "CreateSach", "Sach")
</p>

@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
	<form class="d-flex">
		<input class="form-control me-2 " style="width:300px" type="text placeholder="Search" aria-label="Search" id="SearchString" name="SearchString">
		<input type="date" id="SearchDate" name="SearchDate" />
		<button class="btn btn-outline-success anhtu" type="submit" value="Search">Tìm kiếm</button>

		<button class="btn btn-outline-success anhtu1">@Html.ActionLink("Bỏ tìm kiếm", "Index", "Home")</button>
	</form>

}

<div class="row">
	@foreach (var item in Model)
	{<div class="col-xs-3" style="margin-top:15px">
			<div class="card" style="width: 14rem;">
				<img class="card-img-top" src="@Url.Content(item.HinhBia)" alt="Card image cap" style="height:20rem">
				<div class="card-body">
					<h4 class="card-title">@(item.Ten)</h4>
					<p style="min-height:40px" class="card-text">@(item.TomTat)</p>
					<a href="@Url.Action("Xem1","Home", new { ma = item.Ma })" class="btn btn-primary">Xem</a>
				</div>
			</div>

		</div>
	}
</div>
<div>
	<h4 style="margin-top:10px;">@Html.ActionLink("Quay lại", "PhanLoai", "Sach")</h4>
</div>

WebAppDemo/Views/Home/Xem1.cshtml
@model WebAppDemo.Models.Sach
@{
	ViewBag.Title = "Xem1";
	Layout = "~/Views/Shared/_Layout.cshtml";
}






<div style="margin-top:20px">
	<h4>Chi tiết</h4>
	<hr />
	<div style=" border: 2px solid #706e68; border-radius: 8px;">
		<div style="text-align: left; position:absolute;margin-left:18.5%;margin-top:10px; ">
	
			<img src="@Url.Content(Model.HinhBia)" alt="Image" height="437px" width="324px" style="border-radius: 8px;" />
		</div>
		<dl class="dl-horizontal tada" style="margin-left:48%;margin-top:10px;">

			<dt style="align-content:center;">
				@Html.DisplayNameFor(model => model.Ten)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Ten)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.TomTat)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.TomTat)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Link)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Link)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NgayXuatBan)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NgayXuatBan)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NhaXuatBan)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NhaXuatBan)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.TenTacGia)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.TenTacGia)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.DaXoa)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.DaXoa)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NgayTao)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NgayTao)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NguoiTao)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NguoiTao)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NgaySua)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NgaySua)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NguoiSua)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NguoiSua)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NgayXoa)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NgayXoa)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.NguoiXoa)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.NguoiXoa)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.PhanLoaiSach.TenPhanLoai)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.PhanLoaiSach.TenPhanLoai)
			</dd>

		</dl>
	</div>
</div>
<div style="margin-top:50px;">
	<p style="margin-left:44%;">
		<button type="button" style="height:40px;width:80px;font-size:20px" class="btn btn-success"><a href="@Url.Action( "Edit", "Sach", new { id = Model.Ma })" >Sửa</a> </button>
		<button type="button" style="height:40px;width:80px;font-size:20px" class="btn btn-danger"><a href="@Url.Action( "Delete", "Sach", new { id = Model.Ma })">Xóa</a> </button>

	</p>
</div>

<p style="font-size:20px">


	@Html.ActionLink("Quay lại", "Index", "Home")

</p>

WebAppDemo/Views/Home/hiem.cshtml
@model IEnumerable<WebAppDemo.Models.Sach>

@{
	ViewBag.Title = "hiem";
}

<h3 style="margin-bottom:15px">Sách đã xóa</h3>
<div class="row">
	@foreach (var item in Model)
	{
		<div class="col-xs-3" style="margin-top:15px">
	<div class="card" style="width: 14rem;">
		<img class="card-img-top" src="@Url.Content(item.HinhBia)" alt="Card image cap" style="height:20rem">
		<div class="card-body">
			<h4 class="card-title">@(item.Ten)</h4>
			<p class="card-text">@(item.TomTat)</p>
			<a href="@Url.Action("Xem","Sach", new { ma = item.Ma })" class="btn btn-primary">Restore</a>
		</div>
	</div>

</div>
	}

</div>
<div>
	<h4 style="margin-top:10px;">@Html.ActionLink("Quay lại", "Index", "Home")</h4>
</div>

WebAppDemo/Views/Home/trangchu.cshtml
@{
	ViewBag.Title = "trangchu";
}

<div id="slider">
	<input type="radio" name="slider" id="slide1" checked>
	<input type="radio" name="slider" id="slide2">
	<input type="radio" name="slider" id="slide3">
	<input type="radio" name="slider" id="slide4">
	<div id="slides">
		<div id="overflow">
			<div class="inner">
				<div class="slide slide_1">
					<img src="~/Content/image/bleach.jpg" />
				</div>
				<div class="slide slide_2">
					<div class="slide-content">
						<h2>Slide 2</h2>
						<p>Content for Slide 2</p>
					</div>
				</div>
				<div class="slide slide_3">
					<div class="slide-content">
						<h2>Slide 3</h2>
						<p>Content for Slide 3</p>
					</div>
				</div>
				<div class="slide slide_4">
					<div class="slide-content">
						<h2>Slide 4</h2>
						<p>Content for Slide 4</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="controls">
		<label for="slide1"></label>
		<label for="slide2"></label>
		<label for="slide3"></label>
		<label for="slide4"></label>
	</div>
	<div id="bullets">
		<label for="slide1"></label>
		<label for="slide2"></label>
		<label for="slide3"></label>
		<label for="slide4"></label>
	</div>
</div>